group:
  - repos: |
      conda/actions
      conda/ceps
      conda/clabot-config
      conda/conda
      conda/conda-benchmarks
      conda/conda-bots
      conda/conda-build
      conda/conda-content-trust
      conda/conda-docs
      conda/conda-pack
      conda/conda-package-handling
      conda/conda-prefix-replacement
      conda/conda-verify
      conda/conda_build_test_recipe
      conda/constructor
      conda/cookiecutter-conda-python
      conda/issue-tracker
      conda/menuinst
      conda/pycosat
      conda/schemas
    files:
      - source: .github/workflows/boards.yml
        dest: .github/workflows/boards.yml
      - source: .github/workflows/issues.yml
        dest: .github/workflows/issues.yml
      - source: .github/workflows/labels.yml
        dest: .github/workflows/labels.yml
