group:
  # triaging & label syncing
  - repos: |
      conda/actions
      conda/conda
      conda/conda-benchmarks
      conda/conda-build
      conda/conda-content-trust
      conda/conda-docs
      conda/conda-pack
      conda/conda-package-handling
      conda/conda-prefix-replacement
      conda/conda-verify
      conda/constructor
      conda/cookiecutter-conda-python
      conda/menuinst
      conda/pycosat
      conda/schemas
    files:
      - source: .github/workflows/boards.yml
        dest: .github/workflows/boards.yml
      - source: .github/workflows/issues.yml
        dest: .github/workflows/issues.yml
      - source: .github/workflows/labels.yml
        dest: .github/workflows/labels.yml
  # stale syncing
  - repos: |
      conda/conda
      conda/conda-build
    files:
      - source: .github/workflows/stale.yml
        dest: .github/workflows/stale.yml
  # lock syncing
  - repos: |
      conda/conda
      conda/conda-build
    files:
      - source: .github/workflows/lock.yml
        dest: .github/workflows/lock.yml
