group:
  - repos: |
      conda/actions
      conda/conda
      conda/conda-benchmarks
      conda/conda-build
      conda/conda-content-trust
      conda/conda-docs
      conda/conda-pack
      conda/conda-package-handling
      conda/conda-prefix-replacement
      conda/conda-verify
      conda/constructor
      conda/cookiecutter-conda-python
      conda/issue-tracker
      conda/menuinst
      conda/pycosat
      conda/schemas
    files:
      # beta project
      - source: .github/workflows/project.yml
        dest: .github/workflows/project.yml
      # issue logic
      - source: .github/workflows/issues.yml
        dest: .github/workflows/issues.yml
      # label syncing
      - source: .github/workflows/labels.yml
        dest: .github/workflows/labels.yml
      # stale issues
      - source: .github/workflows/stale.yml
        dest: .github/workflows/stale.yml
      # lock issues
      - source: .github/workflows/lock.yml
        dest: .github/workflows/lock.yml
      # CLA check
      - source: .github/workflows/cla.yml
        dest: .github/workflows/cla.yml
      # epic issue form
      - source: .github/ISSUE_TEMPLATE/epic.yml
        dest: .github/ISSUE_TEMPLATE/epic.yml
