group:
  - repos: |
      conda/conda
      conda/conda-build
    files:
      - source: .github/workflows/boards.yml
        dest: .github/workflows/boards.yml
      - source: .github/workflows/issues.yml
        dest: .github/workflows/issues.yml
      - source: .github/workflows/labels.yml
        dest: .github/workflows/labels.yml
