name: Stale

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: "dryrun: Preview stale issues/prs without marking them (true|false)"
        required: true
        default: "true"
  schedule:
    - cron: 0 4 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: stale_issue
        uses: KJ002/read-yaml@1.5
        with:
          file: .github/messages.yml
          key-path: stale-issue
      - id: close_issue
        uses: KJ002/read-yaml@1.5
        with:
          file: .github/messages.yml
          key-path: close-issue
      - id: stale_pr
        uses: KJ002/read-yaml@1.5
        with:
          file: .github/messages.yml
          key-path: stale-pr
      - id: close_pr
        uses: KJ002/read-yaml@1.5
        with:
          file: .github/messages.yml
          key-path: close-pr
      - uses: actions/stale@v4
        id: stale
        with:
          # Idle number of days before marking issues stale (default: 60)
          days-before-issue-stale: 365
          # Idle number of days before closing stale issues/PRs (default: 7)
          days-before-issue-close: 90
          # Idle number of days before marking PRs stale (default: 60)
          days-before-pr-stale: 360
          # Idle number of days before closing stale PRs (default: 7)
          days-before-pr-close: 30

          # Comment on the staled issues
          stale-issue-message: ${{ steps.stale_issue.outputs.data }}
          # Comment on the staled issues while closed
          close-issue-message: ${{ steps.close_issue.outputs.data }}
          # Comment on the staled PRs
          stale-pr-message: ${{ steps.stale_pr.outputs.data }}
          # Comment on the staled PRs while closed
          close-pr-message: ${{ steps.close_pr.outputs.data }}
          # Label to apply on staled issues
          stale-issue-label: 'stale'
          # Label to apply on closed issues
          close-issue-label: 'stale::closed'
          # Label to apply on staled PRs
          stale-pr-label: 'stale'
          # Label to apply on closed PRs
          close-pr-label: 'stale::closed'

          # Issues with these labels will never be considered stale
          exempt-issue-labels: 'stale::recovered,good-first-issue,help-wanted,severity::1,source::partner,¡important!,¡security!,type::tech-debt,Epic,priority-high'
          # Issues with these labels will never be considered stale
          exempt-pr-labels: 'stale::recovered,good-first-issue,help-wanted,severity::1,source::partner,¡important!,¡security!,type::tech-debt,Epic,priority-high'

          # Max number of operations per run
          operations-per-run: ${{ secrets.STALE_OPERATIONS_PER_RUN || 100 }}
          # Remove stale label from issues/PRs on updates/comments
          remove-stale-when-updated: true

          # Add specified labels to issues/PRs when they become unstale
          labels-to-add-when-unstale: 'stale::recovered'
          labels-to-remove-when-unstale: 'stale,stale::closed'

          # Dry-run (default: false)
          debug-only: ${{ github.event.inputs.dryrun || false }}
          # Order to get issues/PRs (default: false)
          ascending: true
          # Delete branch after closing a stale PR (default: false)
          delete-branch: false

          # Exempt all issues/PRs with milestones from stale
          exempt-all-milestones: true

          # Assignees on issues/PRs exempted from stale
          exempt-assignees: mingwandroid

      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
