name: Sync

on:
  # NOTE: github.event is push payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
  push:
    branches: [main]
    paths:
      - .github/sync.yml  # trigger sync if sync config is modified
      - .github/workflows/sync.yml  # trigger sync if sync workflow is modified
      - .github/workflows/boards.yml
      - .github/workflows/project.yml
      - .github/workflows/issues.yml
      - .github/workflows/labels.yml
      - .github/workflows/stale.yml
      - .github/workflows/lock.yml
      - .github/workflows/cla.yml
      - .github/ISSUE_TEMPLATE/epic.yml

  # NOTE: github.event is workflow_dispatch payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
  workflow_dispatch:

jobs:
  sync:
    if: '!github.event.repository.fork'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BetaHuhn/repo-file-sync-action@v1.16.3
        with:
          GH_PAT: ${{ secrets.SYNC_TOKEN }}
          PR_LABELS: false
          CONFIG_PATH: .github/sync.yml
          COMMIT_EACH_FILE: false
          GIT_USERNAME: Conda Bot
          GIT_EMAIL: conda-bot@users.noreply.github.com
