name: Sync

on:
  push:
    branches: [main]
    paths:
      - .github/sync.yml  # trigger sync if sync config is modified
      - .github/workflows/sync.yml  # trigger sync if sync workflow is modified
      - .github/workflows/boards.yml
      - .github/workflows/issues.yml
      - .github/workflows/labels.yml
  workflow_dispatch:

jobs:
  sync:
    if: '!github.event.repository.fork'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BetaHuhn/repo-file-sync-action@v1.16.3
        with:
          GH_PAT: ${{ secrets.SYNC_TOKEN }}
          PR_LABELS: false
          CONFIG_PATH: .github/sync.yml
          COMMIT_EACH_FILE: false
          GIT_USERNAME: Conda Bot
          GIT_EMAIL: conda-bot@users.noreply.github.com
